config/routes.rb
Rails.application.routes.draw do
 root to: 'pages#home'

 get '/', to: 'pages#home'
 get '/attend', to: 'pages#attend'
 get '/in_company', to: 'pages#in_company'
  post '/in_company', to: 'in_company_requests#create'
 get '/sponsor', to: 'pages#sponsor'


  devise_for :users
  #resources :attend
  resources :events
  # do
  #   resources :attend
  # end
  #resources :sponsor
  resources :workshops
  #resources :in_company
  resources :in_company_requests, only:[:create]


  namespace :admin do
    resources :workshops, :in_company_requests,
    :events, :sponsor_request, :review, :sponsors
   get '/', to: 'pages#home'
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: true
  validates :location, presence: true
end

app/models/in_company.rb
class InCompany < ApplicationRecord
  belongs_to :event

  validates :company_name, presence: true
end

app/models/in_company_request.rb
class InCompanyRequest < ApplicationRecord

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :company_name, presence: true
  validates :email, presence: true
  validates :date, presence: true
  validates :spaces_available, presence: true



end

app/models/review.rb
class Review < ApplicationRecord
  validates :reviewer, presence: true
  validates :review, presence: true
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  validates :company_name, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/workshop.rb
class Workshop < ApplicationRecord
  validates :title, presence: true, length: { maximum: 75 }
  validates :description, presence: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :set_events
  before_action :set_event, only: [:show, :edit, :update, :destroy]

    def index
    end

    def show
    end

    def new
      @event = Event.new
    end

    def create
      @event = Event.new(event_params)

      if @event.save
        redirect_to admin_events_url, :notice => "event successfully created"
      else
        redirect_to admin_events_url, :alert => "Please fill in all required fields"
      end
    end

    def update
      if @event.update_attributes(event_params)
        redirect_to admin_event_url, :notice => "event successfully updated"
      else
        redirect_to admin_events_url, :alert => "Please fill in all required fields"
      end
    end

    def destroy
        @event.destroy
        redirect_to admin_events_url, :notice => "event has been deleted"
    end

    private

    def set_events
      @events = Event.all
    end

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :location, :spaces_available, :date, :public)
    end
  end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  def home
  end
end

app/controllers/admin/sponsor_controller.rb
class Admin::SponsorController < ApplicationController
before_action :set_sponsors
before_action :set_sponsor, only: [:show, :edit, :update]

  def index
  end

  def create
    @sponsor = Sponsor.new(sponsor_params)

    if @sponsor.save
      redirect_to admin_sponsor_index, :notice => "Sponsor successfully created"
    else
      redirect_to admin_sponsor_index, :alert => "Please fill in all required fields"
    end
  end

  def show
  end

  private

  def set_sponsors
    @sponsors = Sponsor.all
  end

  def set_sponsor
    @sponsor = Sponsor.find(params[:id])
  end

  def sponsor_params
    params.require(:sponsor).permit(:company_name, :logo)
  end
end

app/controllers/admin/sponsors_controller.rb
class Admin::SponsorsController < ApplicationController
before_action :set_sponsors
before_action :set_sponsor, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @sponsor = Sponsor.new
  end

  def create
    @sponsor = Sponsor.new(sponsor_params)

    if @sponsor.save
      redirect_to admin_sponsors_url, :notice => "Sponsor successfully created"
    else
      redirect_to admin_sponsors_url, :alert => "Please fill in all required fields"
    end
  end

  def update
    if @sponsor.update_attributes(sponsor_params)
      redirect_to admin_sponsor_url, :notice => "Sponsor successfully updated"
    else
      redirect_to admin_sponsors_url, :alert => "Please fill in all required fields"
    end
  end

  def destroy
    @sponsor.destroy
    redirect_to admin_sponsors_url, :notice => "Sponsor has been deleted"
  end

  private

  def set_sponsors
    @sponsors = Sponsor.all
  end

  def set_sponsor
    @sponsor = Sponsor.find(params[:id])
  end

  def sponsor_params
    params.require(:sponsor).permit(:company_name, :logo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    admin_path
  end
end

app/controllers/in_company_request_controller.rb
class InCompanyRequestController < ApplicationController
  def create
    @in_company_request = InCompanyRequest.new(in_company_request_params)
  end

  private

    def in_company_request_params
      params.require(:in_company_request).permit(:first_name, :last_name,
        :email, :company_name, :email, :date, :spaces_available, :comments,
        :workshop_id)
    end


end

app/controllers/in_company_requests_controller.rb
class InCompanyRequestsController < ApplicationController
  def create
    @in_company_request = InCompanyRequest.new(in_company_request_params)

    if @in_company_request.save!
      redirect_to in_company_path, notice: "Sponsor successfully created"
    else
      redirect_to in_company_path, alert: "Please fill in all required fields"
    end
  end

  private

    def in_company_request_params
      params.require(:in_company_request).permit(:first_name, :last_name,
        :email, :company_name, :email, :date, :spaces_available, :comments,
        :workshop_id)
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
before_action :set_sponsors, :set_events

  def home
  end

  def attend
  end

  def in_company
  end

  def sponsor
  end

  private

  def set_sponsors
    @sponsors = Sponsor.all
  end

  def set_events
    @events = Event.all
  end
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/in_company_request_helper.rb
module InCompanyRequestHelper
end

app/views/admin/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Admin sections</h3>
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-9">
              <h4>Workshops</h4><hr>
            </div>
            <div class="col-md-3 right">
              <%= link_to "View", admin_workshops_path, class: "btn btn-default" %>
            </div>
          </div>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-9">
              <h4>Incompany Requests</h4><hr>
            </div>
            <div class="col-md-3 right">
              <%= link_to "View", admin_in_company_requests_path, class: "btn btn-default" %>
            </div>
          </div>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-9">
              <h4>Events</h4><hr>
            </div>
            <div class="col-md-3 right">
              <%= link_to "View", admin_events_path, class: "btn btn-default" %>
            </div>
          </div>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-9">
              <h4>Sponsors</h4><hr>
            </div>
            <div class="col-md-3 right">
              <%= link_to "View", admin_sponsors_path, class: "btn btn-default" %>
            </div>
          </div>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-9">
              <h4>Sponsor Requests</h4><hr>
            </div>
            <div class="col-md-3 right">
              <%= link_to "View", admin_sponsor_request_index_path, class: "btn btn-default" %>
            </div>
          </div>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-9">
              <h4>Review</h4><hr>
            </div>
            <div class="col-md-3 right">
              <%= link_to "View", admin_review_index_path, class: "btn btn-default" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TocFoxes</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab|Roboto:300,400,500" rel="stylesheet">
  </head>

  <body>
    <div class="page-wrap">
    <%= yield %>
  </div>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/layouts/required_apps.html.erb
<section>
    <div id="apps_section">
      <h1>Get Ready for the Day</h1>
    </div>
    <div id="tools"></div>
      <h2>Know your Tools</h2>
    </div>
    <div id="apps">
      <div id="atom">

      </div>
      <div id="chrome">
        <link type="image/ico" rel="icon" href="//www.google.com/images/icons/product/chrome-32.png">
      </div>
      <div id="slack">
      </div>

    </div>

</section>

app/views/pages/attend.html.erb
<%= render 'shared/navbar' %>
<%= render "shared/company_banner" %>
<%= render "shared/upcoming_events" %>
<%= render "shared/what_will_you_learn" %>
<%= render "shared/ready_for_the_day.html" %>
<div class="col-md-3"></div>
<div class="col-md-9"><%= render "shared/videotestimonial" %></div>
<%= render "shared/testimonials" %>
<%= render "shared/newsletter" %>
<%= render "shared/sponsored_by" %>

app/views/pages/home.html.erb
<a name="about"></a>
  <div class="intro-header">
   <div class="container">
       <div class="row">
           <div class="col-lg-12">
               <div class="intro-message">
                   <h1>Taste of code</h1>
                   <h3>Beginner coding workshop</h3>
                   <hr class="intro-divider">
                   <ul class="list-inline intro-social-buttons">
                       <li>
                           <a <%= link_to "JOIN TOC", attend_path, class: "btn btn-default btn-lg" %></i> <span class="network-name"></span></a>
                       </li>
                       <li>
                           <a <%= link_to "INCOMPANY", in_company_path, class: "btn btn-default btn-lg" %></i> <span class="network-name"></span></a>
                       </li>
                       <li>
                           <a <%= link_to "HOST TOC", sponsor_path, class: "btn btn-default btn-lg" %></i> <span class="network-name"></span></a>
                       </li>
                   </ul>
               </div>
           </div>
       </div>
   </div>
  </div>

app/views/pages/in_company.html.erb
<%= render 'shared/navbar' %>
<%= render "shared/company_banner" %>
<%= render "shared/choose_course" %>
<%= render "shared/get_ready" %>
<%= render "shared/in_company_request" %>

app/views/pages/public.html.erb
<%= render 'shared/navbar' %>
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Taste of Code</h1>
    <p class="lead text-muted">Beginner coding workshop</p>
  </div>
</section>

app/views/pages/sponsor.html.erb
<%= render 'shared/navbar' %>
<%= render "shared/host_next_toc.html.erb" %>

app/views/shared/_choose_course.html.erb
<div class="container">
	<div class="row">
    <h1>Choose your course</h1>
		<h2>Get to know our different types of workshops</h2>
	</div>
</div>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <div class="row">
				<div class="col-lg-2"></div>
				<div class="col-lg-8">
					 <div class="row">
			        <div class="col-lg-4">
			          <img src="http://images.cdn1.stockunlimited.net/clipart/abstract-mountain-background_1598603.jpg" alt="Generic placeholder image" width="140" height="140">
								<h1>Balloons</h1>
			          <p>Sed eget turpis a pede tempor malesuada.</p>
			        </div><!-- /.col-lg-4 -->
			        <div class="col-lg-4">
			          <img src="http://images.cdn1.stockunlimited.net/clipart/abstract-mountain-background_1598603.jpg" alt="Generic placeholder image" width="140" height="140">
								<h1>Feeds Reader</h1>
			          <p>Sed eget turpis a pede tempor malesuada.</p>
			        </div><!-- /.col-lg-4 -->
			        <div class="col-lg-4">
			          <img src="http://images.cdn1.stockunlimited.net/clipart/abstract-mountain-background_1598603.jpg" alt="Generic placeholder image" width="140" height="140">
								<h1>Hangman</h1>
			          <p>Sed eget turpis a pede tempor malesuada.</p>
			        </div>
						</div>
					</div><!-- /.col-lg-4 -->
				<div class="col-lg-2"></div>
			</div>
    </div>
		<div class="item">
      <div class="row">
				<div class="col-lg-2"></div>
				<div class="col-lg-8">
					 <div class="row">
			        <div class="col-lg-4">
			          <img src="http://images.cdn1.stockunlimited.net/clipart/abstract-mountain-background_1598603.jpg" alt="Generic placeholder image" width="140" height="140">
								<h1>Codasseurify</h1>
			          <p>Sed eget turpis a pede tempor malesuada.</p>
			        </div><!-- /.col-lg-4 -->
			        <div class="col-lg-4">
			          <img src="http://images.cdn1.stockunlimited.net/clipart/abstract-mountain-background_1598603.jpg" alt="Generic placeholder image" width="140" height="140">
								<h1>ToDo list</h1>
			          <p>Sed eget turpis a pede tempor malesuada.</p>
			        </div><!-- /.col-lg-4 -->
			        <div class="col-lg-4">
			          <img src="http://images.cdn1.stockunlimited.net/clipart/abstract-mountain-background_1598603.jpg" alt="Generic placeholder image" width="140" height="140">
								<h1>Bob's your uncle</h1>
			          <p>Sed eget turpis a pede tempor malesuada.</p>
			        </div>
						</div>
					</div><!-- /.col-lg-4 -->
				<div class="col-lg-2"></div>
			</div>
    </div>

    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_company_banner.html.erb
<section>
  <div id="top_banner_Company" class="container" style="background: white;">
    <div class="jumbotron"style="background: white;">
      <div class="row">
       <h1 class="text-center">Taste of Code</h1>
      </div>
      <div id="tools" class="row">
        <h3 class="text-center">Beginner Coding Workshop</h3>
      </div>
    </div>
  </div>
</section>

app/views/shared/_get_ready.html.erb
<section>
  <div class="container-fluid">
    <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6" class="center-block">
      <h2 class="text-center">Get Ready for the Day</h2>
      <h3 class="text-center">Requirements</h3>
      <div class="text-center">
        <p>Eiuro, inquit adridens, iniquum, hac quidem de re;</p>
        <p>Universa enim illorum ratione cum tota vestra confligendum puto.</p>
        <p>Indicant pueri, quibus ut in speculis natura cernitur. Illa videamus,</p>
        <p>Nihil acciderat ei, quod nollet, nisi quod anulum, quo delectabatur, in mari abiecerat. </p>
      </div>
    </div>
    <div class="col-md-3"></div>
    </div>
  </div>
</section>

app/views/shared/_host_next_toc.html.erb
<section>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 col-md-offset-3" class="center-block">
        <h1 class="text-center">Host next TOC</h1>
        <h3 class="text-center">Talk to us</h3>
        <form>
          <div class="form-group">
            <input type="first_name" class="form-control" placeholder="First Name">
          </div>
          <div class="form-group">
            <input type="last_name" class="form-control" placeholder="Last Name">
          </div>
          <div class="form-group">
            <input type="company_name" class="form-control" placeholder="Company Name">
          </div>
          <div class="form-group">
            <input type="email" class="form-control" placeholder="Email">
          </div>
          <div class="form-group">
            <input type="date" id="myDate" class="form-control" placeholder="Date">
          </div>
          <div class="form-group">
            <input type="number" class="form-control" placeholder="Number of participants">
          </div>
          <div class="form-group">
            <textarea class="form-control" rows="10" cols="75" placeholder="Comments"></textarea>
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-default">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

app/views/shared/_in_company_request.html.erb
<section>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 col-md-offset-3" class="center-block">
        <h1 class="text-center">Book TOC</h1>
        <h3 class="text-center">Talk to us</h3>
        <div class="container-fluid">
          <div class="row">
            <%= form_for :in_company_request, url: in_company_path do |f| %>
              <div class="form-group"><%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %></div>
              <div class="form-group"><%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %></div>
              <div class="form-group"><%= f.text_field :company_name, class: "form-control", placeholder: "Company Name" %></div>
              <div class="form-group"><%= f.text_field :email, class: "form-control", placeholder: "Email" %></div>
              <div class="form-group"><%= f.collection_select :workshop_id, Workshop.order(:title), :id, :title, prompt: "Please choose a Workshop", class: "form-control" %></div>
              <div class="form-group"><%= f.text_field :date, data: { behavior: "datepicker" }, class: "form-control", placeholder: "DD-MM-YYYY"  %></div>
              <div class="form-group"><%= f.text_field :spaces_available, class: "form-control", placeholder: "Number of participants" %></div>
              <div class="form-group"><%= f.text_field :comments, class: "form-control", placeholder: "Comments" %></div>
              <div class="text-center"><%= f.submit :Submit, class: 'btn btn-success' %></div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_navbar.html.erb
<!-- Fixed navbar -->
   <nav class="navbar navbar-default navbar-static-top">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" <%= link_to "TASTE OF CODE", root_path%></a>
       </div>
       <div id="navbar" class="navbar-collapse collapse">

         <ul class="nav navbar-nav navbar-right">
           <li><a <%= link_to "JOIN TOC", attend_path%></a></li>
           <li><a <%= link_to "INCOMPANY", in_company_path%></a></li>
           <li><a <%= link_to "HOST TOC", sponsor_path%></a></li>
         </ul>
       </div><!--/.nav-collapse -->
     </div>
   </nav>

app/views/shared/_newsletter.html.erb
<section>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6" class="center-block">
        <h2 class="text-center">Join our newsletter</h2>
        <h3 class="text-center">Be the first one to know about our next events</h3>
        <form>
          <div class="form-group">
            <input type="email" class="form-control" placeholder="Email">
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-default">Subscribe</button>
          </div>
        </form>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</section>

app/views/shared/_ready_for_the_day.html.erb
<section>
 <div id="apps_section" class="container">
   <div class="jumbotron">
     <div class="row">
     <h1 style="text-align:center;">Get Ready for the Day</h1>
     </div>
     <div id="tools" class="row">
     <h2 style="text-align:center;">Know your Tools</h2>
     </div>
     <div id="apps" class="row">
       <div id="atom" class="col-md-4">
       <span>Atom</span>
       <a title="Atom" href="https://atom.io" target="_blank">
       <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Atom_editor_logo.svg/2000px-Atom_editor_logo.svg.png" width="50" height="50"/>
       </a>
       </div>
       <div id="chrome" class="col-md-4">
       <span>Chrome</span>
       <a title="Chrome" href="https://www.google.com/chrome/" target="_blank">
       <img src="http://www.rjb-solutions.nl/wp-content/uploads/Google_Chrome_icon_2011.svg.png" width="50" height="50"/>
       </a>
       </div>
       <div id="slack" class="col-md-4">
       <span>Slack</span>
       <a title="Slack" href="https://slack.com/" target="_blank">
       <img src="http://iosicongallery.com/img/512/slack-2014.png" width="50" height="50"/>
       </a>
       </div>
     </div>
   </div>
 </div>
</section>

app/views/shared/_sidebar.html.erb
<div id="sidebar" class="sidebar-offcanvas">
  <div class="col-md-12">
    <h3>Admin</h3>
    <ul class="nav nav-pills nav-stacked">
      <li><%= link_to "Workshops", admin_workshops_path, class: "btn btn-default" %></li>
      <li><%= link_to "Incompany Requests", admin_in_company_requests_path, class: "btn btn-default" %></li>
      <li><%= link_to "Events", admin_events_path, class: "btn btn-default" %></li>
      <li><%= link_to "Sponsors", admin_sponsors_path, class: "btn btn-default" %></li>
      <li><%= link_to "Sponsor Requests", admin_sponsor_request_index_path, class: "btn btn-default" %></li>
      <li><%= link_to "Review", admin_review_index_path, class: "btn btn-default" %></li>
      <hr>
      <li><%= link_to "Log out", destroy_user_session_path, class: "btn btn-default" %></li>
    </ul>
  </div>
</div>

app/views/shared/_sponsor_section_incompany.html.erb
<section>
  <div class="container marketing">
    <div class="row">
      <div class="container">
        <div class="row">
          <h1 style="text-align:center;">Companies we work with</h1>
        </div>
        <div class="row">
          <div class="col-lg-2">
            <img class="img-circle" alt="NOS" width="140" height="140">
          </div>
          <div class="col-lg-2">
            <h3>NOS</h3>
          </div>
          <div class="col-lg-2">
            <img class="img-circle" alt="KPN" width="140" height="140">
          </div>
          <div class="col-lg-2">
            <h3>KPN</h3>
          </div>
          <div class="col-lg-2">
            <img class="img-circle" alt="ABN AMRO" width="140" height="140">
          </div>
          <div class="col-lg-2">
            <h3>ABN AMRO</h3>
          </div>
        </div>
        <div class="row">
        </div>
      <br>
        <div class="row">
          <div class="col-lg-2">
            <img class="img-circle" alt="Rabobank" width="140" height="140">
          </div>
          <div class="col-lg-2">
            <h3>Rabobank</h3>
          </div>
          <div class="col-lg-2">
            <img class="img-circle" alt="TQ" width="140" height="140">
          </div>
          <div class="col-lg-2">
            <h3>TQ</h3>
          </div>
          <div class="col-lg-2">
            <img class="img-circle" alt="J.P. Morgan" width="140" height="140">
          </div>
          <div class="col-lg-2">
            <h3>J.P. Morgan</h3>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_sponsored_by.html.erb
<section>
  <h2 style="text-align:center;">Proudly supported by</h2>
  <div class="container">
    <div class="row">
      <% @sponsors.each do |sponsor| %>
      <div class="col-sm-4">
        <div class="container">
          <div class="row">
            <div class="col-sm-2">
              <%= image_tag(sponsor.logo, size: "100x80") %>
            </div>
            <div class="col-sm-10">
              <p><%= sponsor.company_name %></p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/shared/_upcoming_events.html.erb
<h1 style="text-align:center;">Workshops</h1>
<div class="container marketing">
	<div class="row">
    <% @events.each do |event| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
				<img src=<%= event.image %> style="width:400px;height:228px;">
        <div class="caption">
					<h3><%= event.title %></h3>
					<p>Location: <%= event.location %></p>
		      <p>Spaces available: <%= event.spaces_available %></p>
		      <p>public: <%= event.public %></p>
		      <p>Date: <%= event.date %></p>
        </div>

      </div>
			<script async src="//widgets.nvite.com/1.6/button.js" data-resource="xvgxw4"></script>
    </div>
    <%end%>
  </div>
  </div>

	<hr>

app/views/shared/_videotestimonial.html.erb
<iframe src="https://player.vimeo.com/video/201633032" width="960" height="540" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>