config/routes.rb
Rails.application.routes.draw do
 root to: 'pages#home'

 get '/', to: 'pages#home'
 get '/attend', to: 'pages#attend'
 get '/in_company', to: 'pages#in_company'
  post '/in_company', to: 'in_company_requests#create'
 get '/sponsor', to: 'pages#sponsor'


  devise_for :users
  #resources :attend
  resources :events
  # do
  #   resources :attend
  # end
  #resources :sponsor
  resources :workshops
  #resources :in_company
  resources :in_company_requests, only:[:create]


  namespace :admin do
    resources :workshops, :in_company_requests,
    :events, :sponsor_request, :review, :sponsors
   get '/', to: 'pages#home'
 end
end

app/models/workshop.rb
class Workshop < ApplicationRecord
  validates :title, presence: true, length: { maximum: 75 }
  validates :description, presence: true
end

app/controllers/admin/workshops_controller.rb
class Admin::WorkshopsController < ApplicationController
  before_action :set_workshops
  before_action :set_workshop, only: [:show, :edit, :update, :destroy]
  def index
  end

  def show
  end

  def new
    @workshop = Workshop.new
  end
  def create
    @workshop = Workshop.new(workshop_params)
    if @workshop.save
       redirect_to admin_workshops_url, :notice => "Workshop successfully created"
    else
       redirect_to admin_workshops_url, :alert => "Please fill in all required fields"
    end
  end

  def update
    if @workshop.update_attributes(workshop_params)
      redirect_to admin_workshop_url, :notice => "Workshop successfully updated"
    else
      redirect_to admin_workshops_url, :alert => "Please fill in all required fields"
    end
  end

  def destroy
    @workshop.destroy
    redirect_to admin_workshops_url, :notice => "Workshop has been deleted"
  end

  private

  def set_workshops
  @workshops = Workshop.all
  end
  def set_workshop
  @workshop = Workshop.find(params[:id])
  end
  def workshop_params
   params.require(:workshop).permit(:title, :description, :image, :link_to_live_demo, :link_to_github)
  end
end

app/views/admin/workshops/_form.html.erb
<%= form_for @workshop do |f| %>

  <% @workshop.errors.full_messages.each do |error| %>
    <p class="alert alert-danger" role="alert"><%= error %></p>
  <% end %>

  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, placeholder: "Title", class: "form-control"%>
  </div>

  <div class="form-group">
    <label>Description</label>
  <%= f.text_field :description, placeholder: "Description", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Image</label>
    <%= f.text_field :image, placeholder: "Image", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Live Demo</label>
    <%= f.text_field :link_to_live_demo, placeholder: "Live Demo", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>GitHub Link</label>
    <%= f.text_field :link_to_github, placeholder: "GitHub Link", class: "form-control" %>
  </div>
  
  <div class="actions">
    <%= f.submit (@workshop.new_record? ? "Create" : "Update"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/workshops/edit.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Edit Workshop</h3>
      </div>
      <div class="panel-body">
        <%= render "form" %>
      </div>
    </div>
    <%= link_to "Back", admin_workshops_path, class: "btn btn-default" %>
  </div>
</div>

app/views/admin/workshops/index.html.erb
<div class="container">
  <div class="row">
    <% flash.each do |key, value| %>
     <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>Workshops</h3>
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <% @workshops.each do |workshop| %>
            <div class="col-md-7">
             <h4><%= link_to workshop.title, admin_workshop_url(workshop) %></h4><hr>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", admin_workshop_path(workshop), class: "btn btn-default" %>
            <%= link_to "Edit", edit_admin_workshop_path(workshop), class: "btn btn-default" %>
            <%= link_to "Delete", admin_workshop_path(workshop), class: "btn btn-default", :confirm => "Are you sure?", :method => :delete %>
          </div>
          <% end %>
         </div>
       </div>
     </div>
   </div>
 </div>
</div>
<div class="container">
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>"Add new workshop"</h3>
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <%= link_to "New Workshop", new_admin_workshop_url, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/workshops/new.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>"Add new workshop"</h3>
      </div>
      <div class="panel-body">
        <%= render "form" %>
      </div>
    </div>
    <%= link_to "Back", admin_workshops_path, class: "btn btn-default" %>
  </div>
</div>

app/views/admin/workshops/show.html.erb
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3><%= @workshop.title %></h3>
    </div>
    <div class="panel-body">
        <p>Description: <%= @workshop.description %></p>
        <p>Image: <%= image_tag(@workshop.image, size: "400x300") %>
        <p>Live Demo:<%= video_tag @workshop.link_to_live_demo %>
        <p>GitHub Link:<%= link_to @workshop.link_to_github %>
    </div>
  </div>
    <%= link_to "Back", admin_workshops_path, class: "btn btn-default" %>
</div>