config/routes.rb
Rails.application.routes.draw do
 root to: 'pages#home'

 get '/', to: 'pages#home'
 get '/attend', to: 'pages#attend'
 get '/in_company', to: 'pages#in_company'
  post '/in_company', to: 'in_company_requests#create'
 get '/sponsor', to: 'pages#sponsor'


  devise_for :users
  #resources :attend
  resources :events
  # do
  #   resources :attend
  # end
  #resources :sponsor
  resources :workshops
  #resources :in_company
  resources :in_company_requests, only:[:create]


  namespace :admin do
    resources :workshops, :in_company_requests,
    :events, :sponsor_request, :review, :sponsors
   get '/', to: 'pages#home'
 end
end

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: true
  validates :location, presence: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :set_events
  before_action :set_event, only: [:show, :edit, :update, :destroy]

    def index
    end

    def show
    end

    def new
      @event = Event.new
    end

    def create
      @event = Event.new(event_params)

      if @event.save
        redirect_to admin_events_url, :notice => "event successfully created"
      else
        redirect_to admin_events_url, :alert => "Please fill in all required fields"
      end
    end

    def update
      if @event.update_attributes(event_params)
        redirect_to admin_event_url, :notice => "event successfully updated"
      else
        redirect_to admin_events_url, :alert => "Please fill in all required fields"
      end
    end

    def destroy
        @event.destroy
        redirect_to admin_events_url, :notice => "event has been deleted"
    end

    private

    def set_events
      @events = Event.all
    end

    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :location, :spaces_available, :date, :public)
    end
  end

app/views/admin/events/_form.html.erb
<div class="form-group">
<%= form_for([:admin, @event]) do |f| %>
</div>

<% @event.errors.full_messages.each do |error| %>
  <p class="alert alert-danger" role="alert"><%= error %></p>
<% end %>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title %>
  </div>
<div class="form-group">
  <%= f.label :location %>
  <%= f.text_field :location %>
  </div>

<div class="form-group">
  <%= f.label :spaces_available %>
  <%= f.number_field :spaces_available %>
  </div>

<div class="form-group">
  <%= f.label :date %>
  <%= f.date_select :date %>
  </div>

<div class="form-group">
  <%= f.label :public %>
  <%= f.check_box :public %>
  </div>

<div class="actions">
  <p> <%= f.submit "Save", class: "btn btn-primary" %></p>
<% end %>

app/views/admin/events/edit.html.erb
<%= render "shared/sidebar" %>
<h1>Edit Event</h1>

<%= render "form" %>

app/views/admin/events/index.html.erb
<%= render "shared/sidebar" %>
<div class="container">
  <div class="row">
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>"Current TOC events"</h3>
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <% @events.each do |event| %>
            <div class="col-md-7">
              <h4><%= link_to event.title, admin_event_url(event) %></h4><hr>
            </div>
            <div class="col-md-3 right">
              <%= link_to "View", admin_event_path(event), class: "btn btn-default" %>
              <%= link_to "Edit", edit_admin_event_path(event), class: "btn btn-default" %>
              <%= link_to "Delete", admin_event_path(event), class: "btn btn-default", :confirm => "Are you sure?", :method => :delete %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>"Add new event"</h3>
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <%= link_to "New event", new_admin_event_url, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/events/new.html.erb
<%= render "shared/sidebar" %>
<h1>New Event</h1>

<%= render "form" %>

app/views/admin/events/show.html.erb
<%= render "shared/sidebar" %>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading"><%= @event.title %></div>
    <div class="panel-body">
      <p>Location: <%= @event.location %></p>
      <p>Spaces available: <%= @event.spaces_available %></p>
      <p>public: <%= @event.public %></p>
      <p>Date: <%= @event.date %></p>
      <img src=<%= @event.image %> style="width:304px;height:228px;">
    </div>
  </div>
    <%= link_to "Back", admin_events_path, class: "btn btn-default" %>
</div>