config/routes.rb
Rails.application.routes.draw do
 root to: 'pages#home'

 get '/', to: 'pages#home'
 get '/attend', to: 'pages#attend'
 get '/in_company', to: 'pages#in_company'
  post '/in_company', to: 'in_company_requests#create'
 get '/sponsor', to: 'pages#sponsor'


  devise_for :users
  #resources :attend
  resources :events
  # do
  #   resources :attend
  # end
  #resources :sponsor
  resources :workshops
  #resources :in_company
  resources :in_company_requests, only:[:create]


  namespace :admin do
    resources :workshops, :in_company_requests,
    :events, :sponsor_request, :review, :sponsors
   get '/', to: 'pages#home'
 end
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  validates :company_name, presence: true
end

app/controllers/admin/sponsor_controller.rb
class Admin::SponsorController < ApplicationController
before_action :set_sponsors
before_action :set_sponsor, only: [:show, :edit, :update]

  def index
  end

  def create
    @sponsor = Sponsor.new(sponsor_params)

    if @sponsor.save
      redirect_to admin_sponsor_index, :notice => "Sponsor successfully created"
    else
      redirect_to admin_sponsor_index, :alert => "Please fill in all required fields"
    end
  end

  def show
  end

  private

  def set_sponsors
    @sponsors = Sponsor.all
  end

  def set_sponsor
    @sponsor = Sponsor.find(params[:id])
  end

  def sponsor_params
    params.require(:sponsor).permit(:company_name, :logo)
  end
end

app/controllers/admin/sponsors_controller.rb
class Admin::SponsorsController < ApplicationController
before_action :set_sponsors
before_action :set_sponsor, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @sponsor = Sponsor.new
  end

  def create
    @sponsor = Sponsor.new(sponsor_params)

    if @sponsor.save
      redirect_to admin_sponsors_url, :notice => "Sponsor successfully created"
    else
      redirect_to admin_sponsors_url, :alert => "Please fill in all required fields"
    end
  end

  def update
    if @sponsor.update_attributes(sponsor_params)
      redirect_to admin_sponsor_url, :notice => "Sponsor successfully updated"
    else
      redirect_to admin_sponsors_url, :alert => "Please fill in all required fields"
    end
  end

  def destroy
    @sponsor.destroy
    redirect_to admin_sponsors_url, :notice => "Sponsor has been deleted"
  end

  private

  def set_sponsors
    @sponsors = Sponsor.all
  end

  def set_sponsor
    @sponsor = Sponsor.find(params[:id])
  end

  def sponsor_params
    params.require(:sponsor).permit(:company_name, :logo)
  end
end

app/views/admin/sponsors/edit.html.erb
<%= render "shared/sidebar" %>
<div class="container">
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>"Edit sponsor"</h3>
      </div>
      <div class="panel-body">
        <%= render "form" %>
      </div>
    </div>
    <%= link_to "Back", admin_sponsors_path, class: "btn btn-default" %>
  </div>
</div>

app/views/admin/sponsors/index.html.erb
<%= render "shared/sidebar" %>
<div class="container">
  <div class="row">
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>"Current TOC Sponsors"</h3>
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <% @sponsors.each do |sponsor| %>
            <div class="col-md-7">
              <h4><%= link_to sponsor.company_name, admin_sponsor_url(sponsor) %></h4><hr>
            </div>
            <div class="col-md-3 right">
              <%= link_to "View", admin_sponsor_path(sponsor), class: "btn btn-default" %>
              <%= link_to "Edit", edit_admin_sponsor_path(sponsor), class: "btn btn-default" %>
              <%= link_to "Delete", admin_sponsor_path(sponsor), class: "btn btn-default", :confirm => "Are you sure?", :method => :delete %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>"Add new sponsor"</h3>
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <%= link_to "New Sponsor", new_admin_sponsor_url, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/sponsors/new.html.erb
<%= render "shared/sidebar" %>
<div class="container">
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3>"Add new sponsor"</h3>
      </div>
      <div class="panel-body">
        <%= render "form" %>
      </div>
    </div>
    <%= link_to "Back", admin_sponsors_path, class: "btn btn-default" %>
  </div>
</div>

app/views/admin/sponsors/show.html.erb
<%= render "shared/sidebar" %>
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading"><h3><%= @sponsor.company_name %></h3></div>
    <div class="panel-body">
      <p>Name: <%= @sponsor.company_name %></p>
      <p>Logo: <%= image_tag(@sponsor.logo) %></p>
    </div>
  </div>
    <%= link_to "Back", admin_sponsors_path, class: "btn btn-default" %>
</div>